version: '3'

services:
  database:
    image: postgres:15.3
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clines
    volumes:
      - db_volume:/var/lib/postgresql/data

  api:
    image: caelum/clines-api:1.0
    environment:
      DB_HOST: database
    ports:
      - "8090:8080"

volumes:
  db_volume: